# Dependencies
markdown: kramdown

# Permalinks
permalink: /blog/:categories/:title:output_ext

# Site Setup
title: "타이틀"
tagline: "한줄요약문구"
subtagline: "부제목"
description: "간단 소개문장"

# URLs
url: "https://chano275.github.io"    # 실제 사이트 주소
baseurl: "/"                          # GitHub Pages 루트

# Author Info
name: "정찬호"
email: "chano01794@gmail.com"
linkedin: "https://www.linkedin.com/in/%EC%B0%AC%ED%98%B8-%EC%A0%95-80a083307/"
github:
  repo: "https://github.com/chano275/chano275.github.io"

# Assets
logo: "/favicon-32x32.png"
image: "/favicon-32x32.png"           # 대표 이미지(OG)

# Social Links
social:
  links:
    - "https://github.com/chano275"
    - "https://www.linkedin.com/in/%EC%B0%AC%ED%98%B8-%EC%A0%95-80a083307/"
    - "https://1620-ch.tistory.com/"

# Resume (선택)
# resume: "/assets/resume.pdf"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name:output_ext
